"""create_outbox_events_table

Revision ID: 4d1baf4ed54e
Revises: 001_create_transactions_table
Create Date: 2026-10-01 08:14:50.459084

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4d1baf4ed54e"
down_revision: str | Sequence[str] | None = "001_create_transactions_table"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=36), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PUBLISHED", "FAILED", name="outbox_status_enum"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_outbox_aggregate", "outbox_events", ["aggregate_id"], unique=False
    )
    op.create_index(
        "idx_outbox_status_created",
        "outbox_events",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_events_aggregate_id"),
        "outbox_events",
        ["aggregate_id"],
        unique=False,
    )
    op.drop_index(op.f("idx_customer_id"), table_name="transactions")
    op.drop_index(op.f("idx_status"), table_name="transactions")
    op.create_index(
        op.f("ix_transactions_customer_id"),
        "transactions",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_status"), "transactions", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_status"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_customer_id"), table_name="transactions")
    op.create_index(op.f("idx_status"), "transactions", ["status"], unique=False)
    op.create_index(
        op.f("idx_customer_id"), "transactions", ["customer_id"], unique=False
    )
    op.drop_index(op.f("ix_outbox_events_aggregate_id"), table_name="outbox_events")
    op.drop_index("idx_outbox_status_created", table_name="outbox_events")
    op.drop_index("idx_outbox_aggregate", table_name="outbox_events")
    op.drop_table("outbox_events")
    # ### end Alembic commands ###
